SocialPhotoAppMVC/Controllers/AlbumController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SocialPhotoAppMVC.Services.AlbumService;
using SocialPhotoAppMVC.ViewModels;
using System.Security.Claims;

namespace SocialPhotoAppMVC.Controllers
{
    public class AlbumController : Controller
    {
        private readonly IAlbumService _albumService;
        private readonly IHttpContextAccessor _httpContext;

        public AlbumController(IAlbumService albumService, IHttpContextAccessor httpContext)
        {
            _albumService = albumService;
            _httpContext = httpContext;
        }

        [HttpGet]
        public async Task<IActionResult> RecentAlbums(int? page)
        {
            var recentAlbums = await _albumService.GetAllAlbums(page);

            if (recentAlbums.Success == false)
            {
                var errorMessage = recentAlbums.Message;
                return View("ErrorPage", errorMessage);
            }

            return View(recentAlbums);
        }

        [HttpGet]
        public async Task<IActionResult> AlbumDetail(int id)
        {
            var findAlbum = await _albumService.GetAlbumDetail(id);
            
            if (findAlbum.Success == false)
            {
                var errorMessage = findAlbum.Message;
                return View("ErrorPage", errorMessage);
            }

            return View(findAlbum);
        }

        [HttpGet]
        public async Task<IActionResult> UserAlbums(int? page)
        {
            var albumsPerPage = 6;
            var currentUserId = _httpContext.HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var userPhotos = await _albumService.GetUserAlbums(currentUserId, page, albumsPerPage);

            if (userPhotos.Success == false)
            {
                var errorMessage = userPhotos.Message;
                return View("ErrorPage", errorMessage);
            }
            return View(userPhotos);
        }

        [HttpGet, Authorize]
        public IActionResult CreateAlbum()
        {
            var currentUserId = _httpContext.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            CreateAlbumVM newCreateAlbumVM = new CreateAlbumVM { UserId = currentUserId };
            return View(newCreateAlbumVM);
        }


        [HttpPost, ActionName("CreateAlbum"), Authorize]
        public async Task<IActionResult> CreateAlbumPost(CreateAlbumVM albumVM)
        {
            if (ModelState.IsValid)
            {
                var createAlbum = await _albumService.CreateAlbum(albumVM);
                if (createAlbum.Success == false)
                {
                    TempData["Error"] = $"{createAlbum.Message}";
                    return View(albumVM);
                }
                return RedirectToAction("RecentAlbums");
            }
            else
            {
                ModelState.AddModelError("", "Album was not created.");
                return View(albumVM);
            }
        }

        [HttpGet, Authorize]
        public async Task<IActionResult> DeleteAlbum(int id) 
        {
            string currentUserId = _httpContext.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var albumToRemove = await _albumService.GetAlbumByIdAsync(id);
            if (albumToRemove.Success == false)
            {
                var errorMessage = albumToRemove.Message;
                return View("ErrorPage", errorMessage);
            }

            DeleteAlbumVM deleteAlbumVM = new DeleteAlbumVM
            {
                UserId = currentUserId,
                AlbumOwnerId = albumToRemove.Data.User.Id,
                AlbumId = albumToRemove.Data.Id,
                Title = albumToRemove.Data.Title,
                Description = albumToRemove.Data.Description
            };

            return View(deleteAlbumVM);
        }

        [HttpPost, ActionName("DeleteAlbum"), Authorize]
        public async Task<IActionResult> DeleteAlbumPost(DeleteAlbumVM deleteAlbumVM) 
        {
            if (deleteAlbumVM.UserId == deleteAlbumVM.AlbumOwnerId)
            {
                var result = await _albumService.DeleteAlbum(deleteAlbumVM.AlbumId);
                if (result.Success == true)
                {
                    return RedirectToAction("UserAlbums");
                }
                else
                {
                    var errorMessage = result.Message;
                    return View("ErrorPage", errorMessage);
                }
            }
            else
            {
                var errorMessage = "You are not authorized to delete this album.";
                return View("ErrorPage", errorMessage);
            }
        }

        [HttpGet, Authorize]
        public async Task<IActionResult> EditAlbum(int id) 
        {
            string currentUserId = _httpContext.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var albumToEdit = await _albumService.GetAlbumByIdAsync(id);
            if (albumToEdit.Data == null)
            {
                var errorMessage = albumToEdit.Message;
                return View("ErrorPage", errorMessage);
            }

            EditAlbumVM albumVM = new EditAlbumVM
            {
                AlbumId = albumToEdit.Data.Id,
                Title = albumToEdit.Data.Title,
                Description = albumToEdit.Data.Description,
                CoverArtUrl = albumToEdit.Data.CoverArtUrl,
                CurrentUserId = currentUserId,
                AuthorId = albumToEdit.Data.User.Id,
            };
            return View(albumVM);
        }

        [HttpPost, ActionName("EditAlbum"), Authorize]
        public async Task<IActionResult> EditAlbumPost(EditAlbumVM editAlbumVM) 
        {
            if (editAlbumVM.CurrentUserId == editAlbumVM.AuthorId)
            {
                if (ModelState.IsValid)
                {
                    var result = await _albumService.EditAlbum(editAlbumVM);
                    if (result.Success == false)
                    {
                        var errorMessage = result.Message;
                        return View("ErrorPage", errorMessage);
                    }
                    return RedirectToAction("UserAlbums");
                }
                else
                {
                    ModelState.AddModelError("", "Album edit unsuccessful.");
                    return View(editAlbumVM);
                }
            }
            else
            {
                var errorMessage = "You are not authorized to edit this album.";
                return View("ErrorPage", errorMessage);
            }
        }
    }
}

SocialPhotoAppMVC/Controllers/SearchController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SocialPhotoAppMVC.Enums;
using SocialPhotoAppMVC.Services.SearchService;
using SocialPhotoAppMVC.ViewModels;

namespace SocialPhotoAppMVC.Controllers
{
    public class SearchController : Controller
    {
        private readonly ISearchService _searchService;

        public SearchController(ISearchService searchService)
        {
            _searchService = searchService;
        }

        public IActionResult SearchPhotoIndex() 
        {
            return View();
        }

        public async Task<IActionResult> SearchPhotos(SearchPhotoVM searchInput, int? page)
        {
            var response = await _searchService.SearchPhotos(searchInput, page);

            if (response.Success == false)
            {
                var errorMessage = response.Message;
                return View("ErrorPage", errorMessage);
            }

            return View("PhotoSearchResult", response);
        }

        public IActionResult SearchAlbumIndex()
        {
            return View();
        }

        public async Task<IActionResult> SearchAlbums(SearchAlbumVM searchInput, int? page)
        {
            var response = await _searchService.SearchAlbums(searchInput, page);

            if (response.Success == false)
            {
                var errorMessage = response.Message;
                return View("ErrorPage", errorMessage);
            }

            return View("AlbumsSearchResult", response);
        }

        public IActionResult SearchUserIndex()
        {
            return View();
        }

        public async Task<IActionResult> SearchUsers(SearchUserVM searchInput, int? page) 
        {
            var response = await _searchService.SearchUsers(searchInput, page);

            if (response.Success == false)
            {
                var errorMessage = response.Message;
                return View("ErrorPage", errorMessage);
            }

            return View("UsersSearchResult", response);
        }

    }
}

SocialPhotoAppMVC/Controllers/UserController.cs
using CloudinaryDotNet;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SocialPhotoAppMVC.Services.UserService;
using SocialPhotoAppMVC.ViewModels;
using System.Security.Claims;
using System.Security.Principal;

namespace SocialPhotoAppMVC.Controllers
{
    public class UserController : Controller
    {
        private readonly IHttpContextAccessor _httpContext;
        private readonly IUserService _userService;

        public UserController(IHttpContextAccessor httpContext, IUserService userService)
        {
            _httpContext = httpContext;
            _userService = userService;
        }

        [HttpGet]
        public async Task<IActionResult> ListUsers(int? page)
        {
            var allUsers = await _userService.GetAllUsers(page);

            if (allUsers.Success == false)
            {
                var errorMessage = allUsers.Message;
                return View("ErrorPage", errorMessage);
            }

            return View(allUsers);
        }
        [HttpGet]
        public async Task<IActionResult> UserProfile(string id, int? photosPage, int? albumsPage)
        {
            var photosPerPage = 9;
            var albumsPerPage = 3;
            var userProfile = await _userService.GetUserProfile(id, photosPage, albumsPage, photosPerPage, albumsPerPage);

            if (userProfile.Success == false)
            {
                var errorMessage = userProfile.Message;
                return View("ErrorPage", errorMessage);
            }

            return View(userProfile);
        }

        [HttpGet, Authorize]
        [Route("Identity/Account/Manage/Nickname")]
        public async Task<IActionResult> ChangeNickname() 
        {
            string currentUserId = _httpContext.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var userModel = await _userService.GetUserById(currentUserId);

            var changeNickVM = new ChangeNicknameVM { CurrentUserId = currentUserId, Nickname = userModel.NickName};

            return View(changeNickVM);
        }

        [HttpPost, Authorize]
        [Route("Identity/Account/Manage/Nickname")]
        public async Task<IActionResult> ChangeNickname(ChangeNicknameVM newNick) 
        {
            await _userService.ChangeNickname(newNick);

            return RedirectToAction("ChangeNickname");
        }

        [HttpGet, Authorize]
        [Route("Identity/Account/Manage/ProfilePhoto")]
        public async Task<IActionResult> ChangeProfilePhoto() 
        {
            string currentUserId = _httpContext.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var userModel = await _userService.GetUserById(currentUserId);

            var changeProfilePhotoVM = new ChangeProfilePhotoVM
            {
                CurrentUserId = currentUserId,
                OldProfileImage = userModel.ProfilePictureURL
            };

            return View(changeProfilePhotoVM);
        }

        [HttpPost, Authorize]
        [Route("Identity/Account/Manage/ProfilePhoto")]
        public async Task<IActionResult> ChangeProfilePhoto(ChangeProfilePhotoVM newProfilePhoto)
        {
            await _userService.ChangeProfilePhoto(newProfilePhoto);

            return RedirectToAction("ChangeProfilePhoto");
        }
    }
}

SocialPhotoAppMVC/Views/Search/AlbumsSearchResult.cshtml
@using X.PagedList.Mvc.Core
@model ServiceResponse<X.PagedList.IPagedList<Album>>
@{
    ViewData["Title"] = "Search Result";
}

@*<div class="album py-5 bg-body-tertiary mt-3">
    <div class="container">
        <div class="row">
            <h1 class="text-center mb-4 box-shadow">Search Results</h1>
            @foreach (var item in Model.Data)
            {
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <a asp-controller="Album" asp-action="AlbumDetail" asp-route-id="@item.Id">
                            <img class="card-img-top" src="@item.CoverArtUrl" width="100% height="225" alt="Card image cap">
                        </a>
                        <div class="card-body">
                            <p class="card-text">@item.Title</p>
                        </div>
                    </div>
                </div>
            }
        </div>
        @Html.PagedListPager(Model.Data, page => Url.Action("SearchPhotos", new { page }))
    </div>
</div>*@

<div class="album py-3 bg-body-tertiary">
    <div class="container">
        <h1 class="text-center mb-4">Search Results</h1>
        <div class="row">
            @foreach (var item in Model.Data)
            {
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <a asp-controller="Album" asp-action="AlbumDetail" asp-route-id="@item.Id">
                            <img class="card-img-top" src="@item.CoverArtUrl" width="100% height="225" alt="Card image cap">
                        </a>
                        <div class="card-body">
                            <p class="card-text p-0 m-0 mb-3 text-center rounded-2 bg-body-secondary">@item.User.NickName</p>
                            <h4 class="card-text text-center">@item.Title</h4>
                            <p class="card-text text-center">@item.Description</p>
                        </div>
                    </div>
                </div>
            }
        </div>
        @Html.PagedListPager(Model.Data, page => Url.Action("SearchPhotos", new { page }))
    </div>
</div>

SocialPhotoAppMVC/Views/Search/PhotoSearchResult.cshtml
@using X.PagedList.Mvc.Core
@model ServiceResponse<X.PagedList.IPagedList<Photo>>
@{
    ViewData["Title"] = "Search Result";
}
<div class="album py-5 bg-body-tertiary mt-3">
    <div class="container">
        <div class="row bg-body-tertiary">
            <h1 class="text-center mb-4 box-shadow">Search Results</h1>
            @foreach (var item in Model.Data)
            {
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <a asp-controller="Photo" asp-action="PhotoDetail" asp-route-id="@item.Id">
                            <img class="card-img-top" src="@item.ImageUrl" width="100% height="225" alt="photo thumbnail">
                        </a>
                        <div class="card-body">
                            <p class="card-text">@item.Title</p>
                            <p class="card-text">@item.Description</p>
                        </div>
                    </div>
                </div>
            }
        </div>
        @Html.PagedListPager(Model.Data, page => Url.Action("SearchPhotos", new { page }))
    </div>
</div>

SocialPhotoAppMVC/Views/Search/SearchAlbumIndex.cshtml
@using SocialPhotoAppMVC.Enums;
@using X.PagedList.Mvc.Core
@model SocialPhotoAppMVC.ViewModels.SearchAlbumVM
@{
    ViewData["Title"] = "Search Albums";
}
<div class="w-75 m-auto mt-3">
    <h1>Search albums</h1>
    <form method="post" asp-action="SearchAlbums" enctype="multipart/form-data">
        <div class="form-group">
            <label asp-for="Title">Title</label>
            <input asp-for="Title" class="form-control" placeholder="Title">
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Description">Description</label>
            <input asp-for="Description" class="form-control" placeholder="Description">
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Username">Nickname</label>
            <input asp-for="Username" class="form-control" placeholder="Nickname">
            <span asp-validation-for="Username" class="text-danger"></span>
        </div>

        <button type="submit" class="btn btn-dark mt-3">Search</button>
    </form>
</div>

SocialPhotoAppMVC/Views/Search/SearchPhotoIndex.cshtml
@using SocialPhotoAppMVC.Enums;
@using X.PagedList.Mvc.Core
@model SocialPhotoAppMVC.ViewModels.SearchPhotoVM
@{
    ViewData["Title"] = "Search Photos";
}
<div class="w-75 m-auto mt-3">
    <h1>Search photos</h1>
    <form method="post" asp-action="SearchPhotos" enctype="multipart/form-data">
        <div class="form-group">
            <label asp-for="Title">Title</label>
            <input asp-for="Title" class="form-control" placeholder="Title">
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Description">Description</label>
            <input asp-for="Description" class="form-control" placeholder="Description">
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <div class="form-group mt-2">
            <label asp-for="Category">Category</label>
            <select asp-for="Category" asp-items="@Html.GetEnumSelectList<Category>()">
                <option>--Select--</option>
            </select>
            <span asp-validation-for="Category" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-dark mt-3">Search</button>
    </form>
</div>

SocialPhotoAppMVC/Views/Search/SearchUserIndex.cshtml
@using SocialPhotoAppMVC.Enums;
@using X.PagedList.Mvc.Core
@model SocialPhotoAppMVC.ViewModels.SearchUserVM
@{
    ViewData["Title"] = "Search Users";
}
<div class="w-75 m-auto mt-3">
    <h1>Search users</h1>
    <form method="post" asp-action="SearchUsers" enctype="multipart/form-data">
        <div class="form-group">
            <label asp-for="NickName">NickName/Email</label>
            <input asp-for="NickName" class="form-control" placeholder="NickName/Email">
            <span asp-validation-for="NickName" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-dark mt-3">Search</button>
    </form>
</div>

SocialPhotoAppMVC/Views/Search/UsersSearchResult.cshtml
@using X.PagedList.Mvc.Core
@model ServiceResponse<X.PagedList.IPagedList<AppUser>>
@{
    ViewData["Title"] = "Search Result";
}

<div class="album py-5 bg-body-tertiary mt-3">
    <div class="container">
        <div class="row">
            <h1 class="text-center mb-4 box-shadow">Search Results</h1>
            @foreach (var item in Model.Data)
            {
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <img class="card-img-top rounded-circle p-4" src="@item.ProfilePictureURL" width="100% height="225" alt="Card image cap">
                        <div class="card-body">
                            @if (item.NickName.Length == 0)
                            {
                                <h4 class="card-text text-center">@item.UserName</h4>
                            }
                            else
                            {
                                <h4 class="card-text text-center">@item.NickName</h4>
                            }
                            
                            <p class="card-text text-center">Joined: @item.DateCreated.Date.Year</p>
                            <a asp-controller="User" asp-action="UserProfile" asp-route-id="@item.Id" class="btn btn-sm btn-outline-secondary">View</a>
                        </div>
                    </div>
                </div>
            }
        </div>
        @Html.PagedListPager(Model.Data, page => Url.Action("SearchPhotos", new { page }))
    </div>
</div>