SocialPhotoAppMVC/Models/Album.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.SqlTypes;

namespace SocialPhotoAppMVC.Models
{
    public class Album
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Required, MaxLength(50)]
        public string Title { get; set; }
        [MaxLength(255)]
        public string Description { get; set; }
        public string CoverArtUrl { get; set; } = "https://res.cloudinary.com/dfqrqfs3a/image/upload/v1697360852/logo/nbhvsn7pmjzh5wumus1e.png";
        [DataType(DataType.Date), Column(TypeName = "Date")]
        public DateTime DateCreated { get; set; } = DateTime.Now;
        public AppUser User { get; set; }
        public List<Photo> Photos { get; set; } = new List<Photo>();
    }
}

SocialPhotoAppMVC/Controllers/AlbumController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SocialPhotoAppMVC.Services.AlbumService;
using SocialPhotoAppMVC.ViewModels;
using System.Security.Claims;

namespace SocialPhotoAppMVC.Controllers
{
    public class AlbumController : Controller
    {
        private readonly IAlbumService _albumService;
        private readonly IHttpContextAccessor _httpContext;

        public AlbumController(IAlbumService albumService, IHttpContextAccessor httpContext)
        {
            _albumService = albumService;
            _httpContext = httpContext;
        }

        [HttpGet]
        public async Task<IActionResult> RecentAlbums(int? page)
        {
            var recentAlbums = await _albumService.GetAllAlbums(page);

            if (recentAlbums.Success == false)
            {
                var errorMessage = recentAlbums.Message;
                return View("ErrorPage", errorMessage);
            }

            return View(recentAlbums);
        }

        [HttpGet]
        public async Task<IActionResult> AlbumDetail(int id)
        {
            var findAlbum = await _albumService.GetAlbumDetail(id);
            
            if (findAlbum.Success == false)
            {
                var errorMessage = findAlbum.Message;
                return View("ErrorPage", errorMessage);
            }

            return View(findAlbum);
        }

        [HttpGet]
        public async Task<IActionResult> UserAlbums(int? page)
        {
            var albumsPerPage = 6;
            var currentUserId = _httpContext.HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var userPhotos = await _albumService.GetUserAlbums(currentUserId, page, albumsPerPage);

            if (userPhotos.Success == false)
            {
                var errorMessage = userPhotos.Message;
                return View("ErrorPage", errorMessage);
            }
            return View(userPhotos);
        }

        [HttpGet, Authorize]
        public IActionResult CreateAlbum()
        {
            var currentUserId = _httpContext.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            CreateAlbumVM newCreateAlbumVM = new CreateAlbumVM { UserId = currentUserId };
            return View(newCreateAlbumVM);
        }


        [HttpPost, ActionName("CreateAlbum"), Authorize]
        public async Task<IActionResult> CreateAlbumPost(CreateAlbumVM albumVM)
        {
            if (ModelState.IsValid)
            {
                var createAlbum = await _albumService.CreateAlbum(albumVM);
                if (createAlbum.Success == false)
                {
                    TempData["Error"] = $"{createAlbum.Message}";
                    return View(albumVM);
                }
                return RedirectToAction("RecentAlbums");
            }
            else
            {
                ModelState.AddModelError("", "Album was not created.");
                return View(albumVM);
            }
        }

        [HttpGet, Authorize]
        public async Task<IActionResult> DeleteAlbum(int id) 
        {
            string currentUserId = _httpContext.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var albumToRemove = await _albumService.GetAlbumByIdAsync(id);
            if (albumToRemove.Success == false)
            {
                var errorMessage = albumToRemove.Message;
                return View("ErrorPage", errorMessage);
            }

            DeleteAlbumVM deleteAlbumVM = new DeleteAlbumVM
            {
                UserId = currentUserId,
                AlbumOwnerId = albumToRemove.Data.User.Id,
                AlbumId = albumToRemove.Data.Id,
                Title = albumToRemove.Data.Title,
                Description = albumToRemove.Data.Description
            };

            return View(deleteAlbumVM);
        }

        [HttpPost, ActionName("DeleteAlbum"), Authorize]
        public async Task<IActionResult> DeleteAlbumPost(DeleteAlbumVM deleteAlbumVM) 
        {
            if (deleteAlbumVM.UserId == deleteAlbumVM.AlbumOwnerId)
            {
                var result = await _albumService.DeleteAlbum(deleteAlbumVM.AlbumId);
                if (result.Success == true)
                {
                    return RedirectToAction("UserAlbums");
                }
                else
                {
                    var errorMessage = result.Message;
                    return View("ErrorPage", errorMessage);
                }
            }
            else
            {
                var errorMessage = "You are not authorized to delete this album.";
                return View("ErrorPage", errorMessage);
            }
        }

        [HttpGet, Authorize]
        public async Task<IActionResult> EditAlbum(int id) 
        {
            string currentUserId = _httpContext.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var albumToEdit = await _albumService.GetAlbumByIdAsync(id);
            if (albumToEdit.Data == null)
            {
                var errorMessage = albumToEdit.Message;
                return View("ErrorPage", errorMessage);
            }

            EditAlbumVM albumVM = new EditAlbumVM
            {
                AlbumId = albumToEdit.Data.Id,
                Title = albumToEdit.Data.Title,
                Description = albumToEdit.Data.Description,
                CoverArtUrl = albumToEdit.Data.CoverArtUrl,
                CurrentUserId = currentUserId,
                AuthorId = albumToEdit.Data.User.Id,
            };
            return View(albumVM);
        }

        [HttpPost, ActionName("EditAlbum"), Authorize]
        public async Task<IActionResult> EditAlbumPost(EditAlbumVM editAlbumVM) 
        {
            if (editAlbumVM.CurrentUserId == editAlbumVM.AuthorId)
            {
                if (ModelState.IsValid)
                {
                    var result = await _albumService.EditAlbum(editAlbumVM);
                    if (result.Success == false)
                    {
                        var errorMessage = result.Message;
                        return View("ErrorPage", errorMessage);
                    }
                    return RedirectToAction("UserAlbums");
                }
                else
                {
                    ModelState.AddModelError("", "Album edit unsuccessful.");
                    return View(editAlbumVM);
                }
            }
            else
            {
                var errorMessage = "You are not authorized to edit this album.";
                return View("ErrorPage", errorMessage);
            }
        }
    }
}

SocialPhotoAppMVC/Controllers/PhotoController.cs
using Azure.Core;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection.Extensions;
using SocialPhotoAppMVC.Models;
using SocialPhotoAppMVC.Services;
using SocialPhotoAppMVC.Services.AlbumService;
using SocialPhotoAppMVC.Services.PhotoService;
using SocialPhotoAppMVC.ViewModels;
using System.Net;
using System.Net.Http;
using System.Security.Claims;
using X.PagedList;

namespace SocialPhotoAppMVC.Controllers
{
    public class PhotoController : Controller
    {
        private readonly IPhotoService _photoService;
        private readonly IHttpContextAccessor _httpContext;

        public PhotoController(IPhotoService photoService, IHttpContextAccessor httpContext)
        {
            _photoService = photoService;
            _httpContext = httpContext;
        }

        [HttpGet]
        public async Task<IActionResult> Index(int? page)
        {
            var recentPhotos = await _photoService.GetAllPhotos(page);

            if (recentPhotos.Success == false)
            {
                var errorMessage = recentPhotos.Message;
                return View("ErrorPage", errorMessage);
            }

            return View(recentPhotos);
        }

        [HttpGet]
        public async Task<IActionResult> FeaturedPhotos(int? page)
        {
            var featuredPhotos = await _photoService.GetFeaturedPhotos(page);

            if (featuredPhotos.Success == false)
            {
                var errorMessage = featuredPhotos.Message;
                return View("ErrorPage", errorMessage);
            }

            return View(featuredPhotos);
        }

        [HttpGet]
        public async Task<IActionResult> PhotoDetail(int id, int? page)
        {
            var findPhoto = await _photoService.GetPhotoDetail(id, page);
            if (findPhoto.Success == false)
            {
                var errorMessage = findPhoto.Message;
                return View("ErrorPage", errorMessage);
            }

            return View(findPhoto);
        }

        [HttpGet]
        public async Task<IActionResult> UserPhotos(int? page)
        {
            var currentUserId = _httpContext.HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
            int resultsPerPage = 9;
            var userPhotos = await _photoService.GetUserPhotos(currentUserId, page, resultsPerPage);

            if (userPhotos.Success == false)
            {
                var errorMessage = userPhotos.Message;
                return View("ErrorPage", errorMessage);
            }
            return View(userPhotos);
        }

        [HttpGet, Authorize]
        public async Task<IActionResult> AddPhotoToAlbum(int id)
        {
            var response = await _photoService.AddPhotoToAlbumGET(id);
            if (response.Success == false)
                return View("ErrorPage", response.Message);
            
            return View(response.Data);
        }

        [HttpPost, ActionName("AddPhotoToAlbum"), Authorize]
        public async Task<IActionResult> AddPhotoToAlbum(AddPhotoToAlbumVM photoToAlbumVM) 
        {         
            var addPhotoToAlbum = await _photoService.AddPhotoToAlbumPOST(photoToAlbumVM);
            if (addPhotoToAlbum.Success == false)
            {
                var errorMessage = addPhotoToAlbum.Message;
                return View("ErrorPage", errorMessage);
            }
            return RedirectToAction("UserPhotos");
        }

        [HttpGet, Authorize]
        public async Task<IActionResult> RemovePhotoFromAlbum(int id) 
        {
            var response = await _photoService.RemovePhotoFromAlbumGET(id);
            if (response.Success == false)
                return View("ErrorPage", response.Message);

            return View(response.Data);
        }

        [HttpPost, ActionName("RemovePhotoFromAlbum"), Authorize]
        public async Task<IActionResult> RemovePhotoFromAlbum(AddPhotoToAlbumVM photoToAlbumVM)
        {
            var addPhotoToAlbum = await _photoService.RemovePhotoFromAlbumPOST(photoToAlbumVM);
            if (addPhotoToAlbum.Success == false)
            {
                var errorMessage = addPhotoToAlbum.Message;
                return View("ErrorPage", errorMessage);
            }
            return RedirectToAction("UserPhotos");
        }

        [HttpGet, Authorize]
        public IActionResult UploadPhoto()
        {
            var currentUserId = _httpContext.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            UploadPhotoVM createUploadPhotoVM = new UploadPhotoVM { UserId = currentUserId };
            return View(createUploadPhotoVM);
        }

        [HttpPost, ActionName("UploadPhoto"), Authorize]
        public async Task<IActionResult> UploadPhoto(UploadPhotoVM photoVM)
        {
            if (ModelState.IsValid)
            {
                var uploadPhoto = await _photoService.UploadPhoto(photoVM);
                if (uploadPhoto.Success == false)
                {
                    TempData["Error"] = $"{uploadPhoto.Message}";
                    return View(photoVM);
                }
                return RedirectToAction("UserPhotos");
            }
            else
            {
                ModelState.AddModelError("", "Photo upload unsuccessful.");
                return View(photoVM);
            }           
        }

        [HttpGet, Authorize]
        public async Task<IActionResult> DeletePhoto(int id)
        {
            string currentUserId = _httpContext.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var photoToRemove = await _photoService.GetPhotoByIdAsync(id);
            if (photoToRemove.Success == false)
            {
                var errorMessage = photoToRemove.Message;
                return View("ErrorPage", errorMessage);
            }

            DeletePhotoVM createDeletePhotoVM = new DeletePhotoVM { 
                UserId = currentUserId, 
                PhotoOwnerId = photoToRemove.Data.User.Id,
                PhotoId = id,
                Title = photoToRemove.Data.Title,
                Description = photoToRemove.Data.Description,
                Category = photoToRemove.Data.Category,
            };

            return View(createDeletePhotoVM);
        }

        [HttpPost, ActionName("DeletePhoto"), Authorize]
        public async Task<IActionResult> DeletePhotoPost(DeletePhotoVM deletePhotoVM)
        {
            if (deletePhotoVM.UserId == deletePhotoVM.PhotoOwnerId)
            {
                var result = await _photoService.DeletePhoto(deletePhotoVM.PhotoId);
                if (result.Success == true)
                {
                    return RedirectToAction("UserPhotos");
                }
                else
                {
                    var errorMessage = result.Message;
                    return View("ErrorPage", errorMessage);
                }
            }
            else
            {
                var errorMessage = "You are not authorized to delete this photo.";
                return View("ErrorPage", errorMessage);
            }            
        }

        [HttpGet, Authorize]
        public async Task<IActionResult> EditPhoto(int id)
        {
            string currentUserId = _httpContext.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var photoToEdit = await _photoService.GetPhotoByIdAsync(id);
            if (photoToEdit.Data == null)
            {
                var errorMessage = photoToEdit.Message;
                return View("ErrorPage", errorMessage);
            }

            var photoVM = new EditPhotoVM
            {
                PhotoId = photoToEdit.Data.Id,
                Title = photoToEdit.Data.Title,
                Description = photoToEdit.Data.Description,
                ImageUrl = photoToEdit.Data.ImageUrl,
                Category = photoToEdit.Data.Category,
                CurrentUserId = currentUserId,
                AuthorId = photoToEdit.Data.User.Id,
            };
            return View(photoVM);
        }

        [HttpPost, ActionName("EditPhoto"), Authorize]
        public async Task<IActionResult> EditPhotoPost(EditPhotoVM editPhotoVM)
        {
            if (editPhotoVM.CurrentUserId == editPhotoVM.AuthorId)
            {
                if (ModelState.IsValid)
                {
                    var result = await _photoService.EditPhoto(editPhotoVM);
                    if (result.Success == false)
                    {
                        var errorMessage = result.Message;
                        return View("ErrorPage", errorMessage);
                    }
                    return RedirectToAction("UserPhotos");
                }
                else
                {
                    ModelState.AddModelError("", "Photo edit unsuccessful.");
                    return View(editPhotoVM);
                }  
            }
            else
            {
                var errorMessage = "You are not authorized to edit this photo.";
                return View("ErrorPage", errorMessage);
            }
        }
    }
}

SocialPhotoAppMVC/Views/Album/AlbumDetail.cshtml
@model ServiceResponse<Album>
@{
    ViewData["Title"] = "Album detail";
}

<div class="text-center mt-3">
    @* Album header *@
    <div class="w-75 m-auto">
        <section class="">
            <img class="img-fluid p-3 rounded-5" src="@Model.Data.CoverArtUrl" alt="Card image cap" style="height:300px">
        </section>
        <section class="text-dark mb-3 mb-4 box-shadow pb-4">
            <h1 class=" pt-2 pb-2">@Model.Data.Title</h1>
            <p class="mt-2">@Model.Data.Description</p>
        </section>
    </div>

    @* Photos *@
    <section class="text-dark bg-body-tertiary mb-3 m-auto  mb-4 box-shadow w-75">
        <div class="album py-5 bg-body-tertiary">
            <div class="container">
                <div class="row">
                    @if (Model.Data.Photos.Count() > 0)
                    {
                        @foreach (var item in Model.Data.Photos)
                        {
                            <div class="col-md-4">
                                <div class="card mb-4 box-shadow">
                                    <a asp-controller="Photo" asp-action="PhotoDetail" asp-route-id="@item.Id">
                                        <img class="card-img-top" src="@item.ImageUrl" width="100% height="225" alt="photo thumbnail">
                                    </a>
                                    <div class="card-body">
                                        <h4 class="card-text text-center bg-body-secondary">@item.Title</h4>
                                        <p class="card-text text-center">@item.Description</p>
                                    </div>
                                </div>
                            </div>
                        }
                    }
                    else
                    {
                        <div class="col-md-12 alert alert-danger">
                            <h2>This album is empty.</h2>
                        </div>
                    }
                </div>
            </div>
        </div>
    </section>
</div>

SocialPhotoAppMVC/Views/Album/CreateAlbum.cshtml
@using SocialPhotoAppMVC.ViewModels;
@model CreateAlbumVM

<form class="w-75 m-auto mt-3" method="post" asp-action="CreateAlbum" enctype="multipart/form-data">
    <input type="hidden" id="UserId" name="UserId" asp-for="UserId"></input>
    <div class="form-group">
        <label asp-for="Title">Title</label>
        <input asp-for="Title" class="form-control" placeholder="Title">
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Description">Description</label>
        <input asp-for="Description" class="form-control" placeholder="Description">
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="CoverArt">CoverArt</label>
        <input asp-for="CoverArt" type="file" class="form-control">
        <span asp-validation-for="CoverArt" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-dark">Create album</button>
</form>

SocialPhotoAppMVC/Views/Album/DeleteAlbum.cshtml
@using SocialPhotoAppMVC.ViewModels
@model DeleteAlbumVM
@{
    ViewData["Title"] = "Delete album";
}

<div class="w-75 m-auto mt-3">
    <h1>Are you sure you want to delete this album ?</h1>

    <form method="post" asp-action="DeleteAlbum" enctype="multipart/form-data">
        <input type="hidden" value="AlbumOwnerId" id="AlbumOwnerId" />
        <input type="hidden" value="UserId" id="UserId" />
        <input type="hidden" value="AlbumId" id="AlbumId" />
        <div class="form-group">
            <label asp-for="Title">Title</label>
            <input asp-for="Title" disabled class="form-control" placeholder="Title">
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Description">Description</label>
            <input asp-for="Description" disabled class="form-control" placeholder="Description">
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
    </form>
    <div class="form-group">
        <form action="Delete" method="post">
            <input type="hidden" asp-for="AlbumOwnerId" />
            <input type="hidden" asp-for="UserId" />
            <input type="hidden" asp-for="AlbumId" />
            <input type="submit" value="Delete album" class="btn btn-dark float-right mt-3" />
        </form>
    </div>
</div>

SocialPhotoAppMVC/Views/Album/EditAlbum.cshtml
@using SocialPhotoAppMVC.ViewModels
@model EditAlbumVM
@{
    ViewData["Title"] = "Edit album";
}

<div class="w-75 m-auto mt-3">
    <h1>Album editing</h1>

    <form method="post" asp-action="EditAlbum" enctype="multipart/form-data">
        <input type="hidden" value="AuthorId" id="AuthorId" />
        <input type="hidden" value="CurrentUserId" id="CurrentUserId" />
        <input type="hidden" value="AlbumId" id="AlbumId" />
        <div class="form-group">
            <label asp-for="Title">Title</label>
            <input asp-for="Title" class="form-control" placeholder="Title">
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Description">Description</label>
            <input asp-for="Description" class="form-control" placeholder="Description">
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="NewCoverArt">Choose cover art</label>
            <input type="file" asp-for="NewCoverArt" class="form-control">
            <span asp-validation-for="NewCoverArt" class="text-danger"></span>
        </div>

        <input type="hidden" asp-for="AuthorId" />
        <input type="hidden" asp-for="CurrentUserId" />
        <input type="hidden" asp-for="AlbumId" />
        <input type="hidden" asp-for="CoverArtUrl" />

        <button type="submit" class="btn btn-dark mt-3">Edit album</button>
    </form>
</div>

SocialPhotoAppMVC/Views/Album/RecentAlbums.cshtml
@using X.PagedList.Mvc.Core
@model ServiceResponse<X.PagedList.IPagedList<Album>>
@{
    ViewData["Title"] = "New Albums";
}

<div class="album py-3 bg-body-tertiary">
    <div class="container">
        <h1 class="text-center mb-4">New albums</h1>
        <div class="row">
            @foreach (var item in Model.Data)
            {
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <a asp-controller="Album" asp-action="AlbumDetail" asp-route-id="@item.Id">
                            <img class="card-img-top" src="@item.CoverArtUrl" width="100% height="225" alt="Card image cap">
                        </a>
                        <div class="card-body">
                            <p class="card-text p-0 m-0 mb-3 text-center rounded-2 bg-body-secondary">@item.User.NickName</p>
                            <h4 class="card-text text-center">@item.Title</h4>
                            <p class="card-text text-center">@item.Description</p>
                        </div>
                    </div>
                </div>
            }
        </div>
        @Html.PagedListPager(Model.Data, page => Url.Action("Index", new { page }))
    </div>
</div>

SocialPhotoAppMVC/Views/Album/UserAlbums.cshtml
@using X.PagedList.Mvc.Core
@model ServiceResponse<X.PagedList.IPagedList<Album>>
@{
    ViewData["Title"] = "My Albums";
}

<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <h1 class="text-center mb-4">My albums</h1>
        <div class="row">
            @foreach (var item in Model.Data)
            {
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <a asp-controller="Album" asp-action="AlbumDetail" asp-route-id="@item.Id">
                            <img class="card-img-top" src="@item.CoverArtUrl" width="100% height="225" alt="photo thumbnail">
                        </a>
                        <div class="card-body d-flex flex-column align-items-center">
                            <h4 class="card-text text-center">@item.Title</h4>
                            <p class="card-text text-center">@item.Description</p>
                            <div>
                                <a asp-controller="Album" asp-action="DeleteAlbum" asp-route-id="@item.Id" class="btn btn-sm btn-outline-secondary">Delete</a>
                                <a asp-controller="Album" asp-action="EditAlbum" asp-route-id="@item.Id" class="btn btn-sm btn-outline-secondary">Edit</a>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
        @Html.PagedListPager(Model.Data, page => Url.Action("UserAlbums", new { page }))
    </div>
</div>